name: CI/CD Deployment to GKE

on:
  push:
    branches: [main]

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GKE_CLUSTER: "my-cluster"
  GKE_REGION: "us-central1"
  DEPLOYMENT_NAME: "mlops-app"
  IMAGE_BASE: "us-central1-docker.pkg.dev/flash-district-467713-g8/my-repo/mlops-app"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Authenticate with GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GCR
        run: |
          gcloud auth configure-docker us-central1-docker.pkg.dev --quiet

      - name: Build and Push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: |
            ${{ env.IMAGE_BASE }}:${{ github.sha }}
            ${{ env.IMAGE_BASE }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Set up GKE credentials
        run: |
          # Add Google Cloud SDK repository
          sudo apt-get update
          sudo apt-get install -y apt-transport-https ca-certificates gnupg
          echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
          curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key --keyring /usr/share/keyrings/cloud.google.gpg add -
          sudo apt-get update
          sudo apt-get install -y google-cloud-sdk-gke-gcloud-auth-plugin
          
          # Configure kubectl
          echo "export USE_GKE_GCLOUD_AUTH_PLUGIN=True" >> $GITHUB_ENV
          gcloud container clusters get-credentials $GKE_CLUSTER \
            --region $GKE_REGION \
            --project $PROJECT_ID

      - name: Deploy to GKE
        run: |
          kubectl apply -f kubernetes-deployment.yaml
          kubectl set image deployment/$DEPLOYMENT_NAME \
            $DEPLOYMENT_NAME=$IMAGE_BASE:$GITHUB_SHA
          kubectl rollout status deployment/$DEPLOYMENT_NAME --timeout=300s || \
            (kubectl describe deployment/$DEPLOYMENT_NAME && \
             kubectl logs -l app=$DEPLOYMENT_NAME --all-containers=true --tail=50 && \
             exit 1)